# Generated by Django 5.2.7 on 2025-10-24 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('etf', 'ETF'), ('bond', 'Bond')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
